### PR TITLE
Fixes for 'checksum was invalid' issue.

### PR DESCRIPTION
**Pull request by sars**

### CODE REVIEW

**Comment by sars** [comment]
According to async-props doc https://github.com/rackt/async-props#server we need to print their script tag to define **ASYNC_PROPS** global var

**Comment by bdefore** [comment]
Thanks @sars looks good. I'll verify with the starter project this evening.

**Comment by bdefore** [comment]
This fix is included in 3.0.0-rc7

**Comment by sars** [comment]
@bdefore Thanks!

**Pull request merged**
