### PR TITLE
Upgraded react-router-redux 3.0.0 -> 4.0.0

### PR DESCRIPTION
**Pull request by nathanielks**

### CODE REVIEW

**Comment by nathanielks** [comment]
Herp derp, realized I need to update a few more things.

**Comment by nathanielks** [comment]
okie smokie, this is ready :+1:

**Comment by bdefore** [comment]
This looks like it no longer registers the react-router-redux middleware for the client?

**Comment by nathanielks** [comment]
4.0 introduced breaking changes where I don't believe middleware is required anymore. That said, not sure if thats the case and I unfortunately keep finding bugs with this. Nested routes get redirected to the first and not sure why yet. I wish there was a "oh wait, not yet label" :neutral_face:

**Comment by nathanielks** [comment]
Wanted to contribute more than just a bug report and here were are :expressionless:

**Comment by nathanielks** [comment]
And what do you know! Middleware is still applicable, gonna give that a try. Sorry for the noise and I appreciate all the work you've done!

**Comment by bdefore** [comment]
Yeah my takeaway on the 4.0.0 release is that the API changes with React Router 2.0 negated a lot of the need for react-router-redux, so they've removed a lot of previous functionality. For this reason I'm not sure it's worth updating from 3.0.0. They've also implied that development is finished 'for the foreseeable future' in the changelog: https://github.com/reactjs/react-router-redux/blob/master/CHANGELOG.md.

**Comment by nathanielks** [comment]
All good points. Thanks again for your time! :+1:

**Pull request closed without merging**
