### PR TITLE
Properly implement syncReduxAndRouter

### PR DESCRIPTION
**Pull request by stephenbaldwin**

### CODE REVIEW

**Comment by bdefore** [comment]
This should no longer be necessary after an update to the latest redux-simple-router https://github.com/rackt/redux-simple-router/blob/master/CHANGELOG.md#202

**Comment by stephenbaldwin** [comment]
Docs claim that 2.x uses redux-simple-router 1.x (https://github.com/bdefore/universal-redux#2x). We should either throw this in or update readme

**Comment by bdefore** [comment]
Ah, you're right. We'll need to bring in your changes then, thanks.

**Comment by bdefore** [comment]
@stephenbaldwin Published with 2.4.7. Thanks.

**Pull request merged**
