### PR TITLE
Feature/separate dev deps

### PR DESCRIPTION
**Pull request by chrisblossom**
Here is a proposed solution for #2. I am not sure how well this will work on npm@2.

Just noticed it is on the old 0.x branch. If you want to move forward with this solution, I can merge into the other branches as well.

```
npm install --production
ls node_modules
babel                  compression            file-loader            lodash                 query-string           react-document-meta    react-router           redux-router
babel-plugin-typecheck express                history                pretty-error           react                  react-dom              redux


NODE_ENV=production npm install
ls node_modules
babel                  compression            file-loader            lodash                 query-string           react-document-meta    react-router           redux-router
babel-plugin-typecheck express                history                pretty-error           react                  react-dom              redux


npm install
ls node_modules
autoprefixer-loader          compression                  history                      mocha                        react-transform-catch-errors serve-favicon
babel                        css-loader                   json-loader                  node-sass                    react-transform-hmr          strip-loader
babel-core                   eslint                       karma                        phantomjs                    redbox-react                 style-loader
babel-eslint                 eslint-config-airbnb         karma-cli                    phantomjs-polyfill           redux                        url-loader
babel-loader                 eslint-loader                karma-mocha                  pretty-error                 redux-devtools               webpack
babel-plugin-react-transform eslint-plugin-import         karma-mocha-reporter         query-string                 redux-devtools-dock-monitor  webpack-config-merger
babel-plugin-typecheck       eslint-plugin-react          karma-phantomjs-launcher     react                        redux-devtools-log-monitor   webpack-dev-middleware
babel-runtime                express                      karma-sourcemap-loader       react-addons-test-utils      redux-logger                 webpack-error-notification
bootstrap-sass               extract-text-webpack-plugin  karma-webpack                react-document-meta          redux-router                 webpack-hot-middleware
bootstrap-sass-loader        file-loader                  less                         react-dom                    sass-loader                  webpack-isomorphic-tools
chai                         font-awesome                 less-loader                  react-redux                  scroll-behavior
clean-webpack-plugin         font-awesome-webpack         lodash                       react-router                 serialize-javascript
```

### CODE REVIEW

**Comment by chrisblossom** [comment]
Not sure how your commits got included in this. Sorry about that. Should I put a new PR in?

**Comment by bdefore** [comment]
@chrisblossom the other commits are probably from your branching from master at a different time than i did on `0.x` ... I meant to cherry pick those in anyway.

I'll have a look at this shortly thanks!

**Comment by bdefore** [comment]
@chrisblossom can you elaborate on how you're constructing the `npmPath` in the postinstall script here?

```
var npmPath = path.resolve(path.dirname(process.env.npm_execpath), '../');
var npm = require(npmPath);
```

I'm failing on npm install of your feature branch with:

```
Error: Cannot find module '/Users/d4/.nvm/versions/node/v4.1.1/lib/node_modules/npm3/node_modules'
```

The full output: https://gist.github.com/bdefore/a5f9cc7677ad36f25b17

**Comment by bartolkaruza** [comment]
Just an idea on this: Maybe the NODE_ENV=production check is a bit limiting, say if you have multiple environments that get CI deployments (test, acceptance), but only one dev environment (local machines). Inverting the logic to only install dev dependencies if NODE_ENV=development would solve this?

**Comment by chrisblossom** [comment]
@bdefore npm_execpath is an environmental variable set when npm is ran (by npm). npm_execpath is equal to where npm's npm-cli.js script is located. I am not sure if the error you are getting is because of a bug in an older version of npm@3 or because maybe there needs to be some additional logic built into finding where npm lives.

@bartolkaruza I think it is best mimic npm's behavior in regards to devDependencies. I think the only time npm will not install devDependencies is when the --production flag is set, or when NODE_ENV=production.

**Comment by chrisblossom** [comment]
@bdefore @bartolkaruza What do you guys think about the latest implementation? Is there still an npm install error?

I removed the webDevDependencies and instead just put them all into devDependencies then npm install all devDeps if it isn't in production and is installed as a module.

Any ideas how to better solve this?

**Comment by bdefore** [comment]
i suspect you're right @chrisblossom that there's a difference in how we installed npm3. i installed mine `-g` for node 4. are you using 5? i'll try again to run it in a few hours.

**Comment by chrisblossom** [comment]
With the updated PR, I copied how npm requires itself, so it should be fixed across all versions. There is a comment right above the npm require line describing it.

```
node --version
v4.2.3

npm --version
3.5.2
```

**Comment by iarna** [comment]
FYI: Calling directly into npm internals like this is not supported. The way the internal functions are laid out is not a part of our semver contract and can and will be changed without notice. If you want to call `npm`, please use a `child_process` with `exec` or `spawn`.

**Comment by chrisblossom** [comment]
Thanks for the response @iarna. I actually had an implementation like that earlier, but it just seemed a bit messier. I'll revert back to that per your recommendation.

Is there a better solution to this problem besides re-calling npm that you can think of?

**Comment by iarna** [comment]
As I said over in https://github.com/npm/npm/issues/10814, I think you're swimming against the current on this one. I think a `universal-redux-dev` type module that can be a dev dependency of both `universal-redux` and used by users of `universal-redux` as a dev dependency too is gonna be the way to go.

**Comment by bartolkaruza** [comment]
I also agree that a dev module dependency would be much cleaner. Allows the main server implementation also to be implemented with full flexibility, for example with koa instead of express, or any other variation people would want to use for their main server. Any project wanting to use the setup could choose to just use universal-redux-dev (build and dev time tooling) or both universal-redux (standard universal setup for production) and universal-redux-dev. When using universal-redux, the universal-redux-dev becomes mandatory in your devDependencies.

**Comment by bdefore** [comment]
@bartolkaruza you present a good case about how some users would like to use koa, hapi, or something else, and it'd be nice if this library didn't proscribe that part. perhaps rather than universal-redux and universal-redux-dev, it could split along the lines of universal-redux and universal-redux-express (and universal-redux-koa, etc.) with the latter part composed mostly of `src/server.js` and its scripts and helpers.

@chrisblossom i was able to get your newest changes to install cleanly. one question i have: wouldn't this still end up downloading all of the rest of the dependencies if you run the build step on the production deploy? this is currently how my setup works.

i think for right now i'd prefer not to bring these changes into the main repo. apart from the unconventional npm install, i'm not sure how this will work with npm2, which i intend to support for 0.x.

**Comment by chrisblossom** [comment]
@bdefore which build step are you referring to? If NODE_ENV or the --production flag is set it will not install the development dependencies. npm2 should work with this solution as it just installs all of the dev dependencies listed in package.json via command line npm.  This runs the command `npm install autoprefixer-loader@^3.1.0 babel-core@~5.8.33 babel-eslint@^4.1.3 ... webpack-isomorphic-tools@^2.2.18` as you would in terminal.

I do agree with iarna and @bartolkaruza that having a separate dev repo is the best way to solve this issue. Not having this awkward additional npm build step would be preferred, but it would require stripping out the development code into its own codebase.

**Comment by bdefore** [comment]
@chrisblossom i was referring to the `bin/build.js` script that is exported as `universal-redux-build`, this is what projects use to generate `static/dist/main-{hash}.js` and `static/dist/main-{hash}.css` which the Express server then serves up. i use this as a `postinstall` step to indicate to heroku to do a webpack build before running the script in `bin/server.js` on `npm start`

i didn't realize npm2 could work with this too. i'll give that a shot later.

**Pull request closed without merging**
